# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20171224_1938'),
        ('images', '0003_auto_20171224_0415'),
    ]

    operations = [
    ]
